# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.5.1
_src_path: https://github.com/jupyterlab/extension-template
author_email: ''
author_name: Developer
has_ai_rules: false
has_binder: false
has_settings: false
kind: frontend
labextension_name: jupyterlab_notebook_edit_time
project_short_description: Track total editing time in Jupyter notebooks
python_name: jupyterlab_notebook_edit_time
repository: https://github.com/example/jupyterlab_notebook_edit_time
test: false

